M48
; DRILL file {KiCad 9.0.5} date 2025-12-05T08:19:09+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-05T08:19:09+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X170.2Y-119.25
T2
X141.4Y-106.7
X149.4Y-55.7
X190.5Y-55.75
X198.4Y-106.7
M30
