M48
; DRILL file {KiCad 9.0.5} date 2025-12-09T08:08:33+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-09T08:08:33+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X170.2Y-119.25
T2
X141.0Y-108.0
X146.98Y-62.955
X189.48Y-62.955
X199.0Y-108.0
M30
