#!/usr/bin/env python3
"""
generate_web_assets.py — Regenerates firmware/src/WebAssets.h from firmware/www/

Reads app.css and htmx.min.js from firmware/www/, converts each to a PROGMEM
hex array, computes an FNV-1a 32-bit content hash for cache-busting, and writes
firmware/src/WebAssets.h.

Usage:
    python3 tools/generate_web_assets.py [--check]

    --check  Exit with code 1 if WebAssets.h would change (for CI consistency checks).
             Does not write any files.

This script is the single source of truth for WebAssets.h. Never edit that file
by hand — run this script instead.
"""

import hashlib
import sys
from pathlib import Path

# ── Configuration ──

REPO_ROOT = Path(__file__).resolve().parent.parent
WWW_DIR = REPO_ROOT / "firmware" / "www"
OUTPUT_FILE = REPO_ROOT / "firmware" / "src" / "WebAssets.h"

# (source filename, C variable prefix)
ASSETS = [
    ("app.css", "app_css"),
    ("htmx.min.js", "htmx_js"),
]


def fnv1a_32(data: bytes) -> str:
    """Compute FNV-1a 32-bit hash, return 8-char hex string."""
    h = 0x811C9DC5
    for b in data:
        h ^= b
        h = (h * 0x01000193) & 0xFFFFFFFF
    return f"{h:08x}"


def format_hex_array(data: bytes, indent: str = "  ") -> str:
    """Format bytes as a C PROGMEM hex array (16 bytes per line)."""
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        suffix = "," if i + 16 < len(data) else ""
        lines.append(f"{indent}{hex_vals}{suffix}")
    return "\n".join(lines)


def generate_header() -> str:
    """Generate the full WebAssets.h content."""
    parts = []
    parts.append("#pragma once")
    parts.append("")
    parts.append("// Embedded web assets — served from flash, no SD card required")
    parts.append("//")
    parts.append("// Auto-generated by tools/generate_web_assets.py — DO NOT EDIT BY HAND.")
    parts.append("// Source files: firmware/www/app.css, firmware/www/htmx.min.js")
    parts.append("// Regenerate with: python3 tools/generate_web_assets.py")
    parts.append("")

    for filename, prefix in ASSETS:
        filepath = WWW_DIR / filename
        data = filepath.read_bytes()
        hex_array = format_hex_array(data)
        hash_hex = fnv1a_32(data)

        parts.append(f"// {filename} ({len(data)} bytes, content hash: {hash_hex})")
        parts.append(f"static const unsigned char {prefix}_data[] PROGMEM = {{")
        parts.append(hex_array)
        parts.append("};")
        parts.append(f"static const unsigned int {prefix}_len = {len(data)};")
        parts.append(f"static const char {prefix}_hash[] = \"{hash_hex}\";")
        parts.append("")

    return "\n".join(parts) + "\n"


def main() -> int:
    check_only = "--check" in sys.argv

    # Validate source files exist
    for filename, _ in ASSETS:
        filepath = WWW_DIR / filename
        if not filepath.exists():
            print(f"ERROR: Source file not found: {filepath}", file=sys.stderr)
            return 1

    generated = generate_header()

    if check_only:
        existing = OUTPUT_FILE.read_text() if OUTPUT_FILE.exists() else ""
        if generated != existing:
            print(
                f"ERROR: {OUTPUT_FILE.name} is out of date. "
                "Run: python3 tools/generate_web_assets.py",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {OUTPUT_FILE.name} is up to date.")
        return 0

    OUTPUT_FILE.write_text(generated)
    print(f"Generated {OUTPUT_FILE}")
    for filename, prefix in ASSETS:
        filepath = WWW_DIR / filename
        data = filepath.read_bytes()
        print(f"  {filename}: {len(data)} bytes, hash={fnv1a_32(data)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
