[platformio]
default_envs = thingplus_s3_usb_cdcserial

[env:thingplus_s3_usb_uartserial]
platform = espressif32
board = sparkfun_esp32s3_thing_plus
framework = arduino

; Use your project-local variant/pins
board_build.variants_dir = variants

; Arduino default from boards.txt
board_build.partitions = default.csv

monitor_speed = 115200

; USB settings: upload over USB, but keep Serial on UART (more conservative)
build_unflags = -std=gnu++11 -std=gnu++14 -std=gnu++17
build_flags =
  -std=gnu++2a
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=0

lib_deps =
  adafruit/Adafruit BusIO
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  bblanchon/ArduinoJson
  greiman/SdFat

; --- Optional: if you want Serial over USB CDC instead of UART ---
[env:thingplus_s3_usb_cdcserial]
platform = espressif32
board = sparkfun_esp32s3_thing_plus
framework = arduino
board_build.variants_dir = variants
board_build.partitions = default.csv
monitor_speed = 115200

build_unflags = -std=gnu++11 -std=gnu++14 -std=gnu++17
build_flags =
  -std=gnu++2a
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
  adafruit/Adafruit BusIO
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  bblanchon/ArduinoJson
  greiman/SdFat